#pragma once
#include <cstddef> // for std::size_t
#include <string>
#include <vector>

namespace globals 
{

	namespace ui
	{
		inline bool assetspawn = false;
		inline bool foodspawn = false;
        inline bool playerlistwindow = false;
	}


	namespace player
	{
		inline bool spinbot = false;
		inline bool developer = false;
        inline bool fovtoggle = false;
        inline bool speedtoggle = false;
        inline bool changespeed = false;
		inline float fov = 60.0f;
        inline float speed = 3.5f;
	}

	namespace inventory
	{
		inline bool unlockkeys = false;
		inline bool sharecamera = false;
		inline bool steamercamera = false;
		inline bool clothingcustomizer = false;
		inline bool clothing = false;
		
	}

	namespace movement
	{
		inline bool dynamicfly = false;
		inline bool staticfly = false;
	}


	struct Vector3f {
		float x;
		float y;
		float z;
	};

	struct Quaternion4f {
		float x;
		float y;
		float z;
		float w;
	};

    struct Vector3 {
        float x;
        float y;
        float z;
    };

	namespace network
	{
		inline bool disableuneqipfromslots = false;
		inline bool disablegotoroom = false;
		inline bool disablebannercv2 = false;
		inline bool disableramcrashcheer = false;
		inline bool disableramcrashbullets = false;

		inline bool foodsploit = false;
		inline bool customfood = false;
		inline bool customfoodsize = false;
		inline bool customfoodposition = false;
		inline bool customfoodrotation = false;
		inline bool customfoodamount = false;
		inline bool randomrotation = false;
		inline bool foodassetspawn = false;

		inline float foodsize = 1.0f;
		inline int foodcount = 1;
		inline Vector3f foodposition = { 0, 0, 0};
		inline Quaternion4f foodrotation = { 0, 0, 0, 0 };
		


		typedef struct Food
		{
			const char* frie;
			const char* guid;
		} Food;
		//  Food Liste (NEW)
        struct PlayerData {
            std::string name;
            int playerId;
            void* playerAddress;
            void* photonPlayerAddress;
            void* networkedViewAddress;
            Vector3 position;      // World position
            Vector3 screenPosition; // Screen position
        };
        inline std::vector<PlayerData> playerList;

        inline void ClearPlayers() {
            playerList.clear();
        }

        inline size_t GetPlayerCount() {
            return playerList.size();
        }

        inline PlayerData* FindPlayerByName(const std::string& name) {
            for (auto& player : playerList) {
                if (player.name == name) {
                    return &player;
                }
            }
            return nullptr;
        }

        inline void* FindPlayerById(int playerId) {
            for (auto& player : playerList) {
                if (player.playerId == playerId) {
                    return player.playerAddress;
                }
            }
            return nullptr;
        }

        inline std::string selectedPlayerName = "";
        inline int selectedPlayerId = -1;
        inline bool teleportToPlayer = false;
        inline bool voidplayers = false;
        inline bool witchorbit = false;
        inline int targetPlayerId = -1;
        inline bool refreshPlayerList = false;
        inline bool sendnotification = false;
        inline bool disarm = false;
        inline bool disarmall = false;
        inline bool ramcrash = false;
        inline bool bring = false;
        static ImVec2 PlayerListPos;
        static ImVec2 PlayerListSize;
        typedef struct Il2CppArray
        {
            void* klass;
            void* monitor;
            void* bounds;
            size_t max_length;
            void* vector[32];
        } Il2CppArray;


        inline const char* list[] = {
        "((CheerBadge))",
        "((NameTag_YourProfile_Preview))",
        "((NametagIconWIthDropShadow))",
        "((PlayerRoleBadge))",
        "[AccountStatusDialogScreen]",
        "[AddRemovePlayerRoomRoleButton]",
        "[AddRemovePlayersRoomRolesDialog]",
        "[AgeDialogScreen]",
        "[AISettingsScreen]",
        "[AmbienceRadio]",
        "[AnimationGizmo]",
        "(AnimationGizmo_V2)",
        "[AnimationGizmoSplineStep]",
        "[Arena_AutomaticGun]",
        "[Arena_Cyber_Beam_Charge_VFX]",
        "[Arena_Cyber_Beam_Embers_VFX]",
        "[Arena_Cyber_Beam_ImpactSparks_VFX]",
        "[Arena_Cyber_Beam_MuzzleFlash_VFX]",
        "[Arena_Cyber_TrashBag_Sandbox] Variant",
        "[Arena_Cyberjunk_BasicEncounter]",
        "[Arena_Cyberjunk_BasicEncounter_Rats]",
        "[Arena_Cyberjunk_BasicEncounter_Rats_Elite]",
        "[Arena_Cyberjunk_EliteAirGroundEncounter]",
        "[Arena_Cyberjunk_EliteFlyingEncounter]",
        "[Arena_Cyberjunk_EliteGroundEncounter]",
        "[Arena_EMP]",
        "[Arena_EnemyCombatUI_3D]",
        "[Arena_Grenade]",
        "[Arena_Grenade_Explosion_VFX]",
        "[Arena_Grenade_Explosion_VFX] JumboTron Variant",
        "[Arena_Hangar2_MainframeWaveCenterEncounter]",
        "[Arena_Hangar2_MainframeWaveLeftEncounter]",
        "[Arena_Hangar2_MainframeWaveRightEncounter]",
        "[Arena_Hangar3_BasicEncounter]",
        "[Arena_Hangar3_EliteFlyingEncounter]",
        "[Arena_Hangar3_EliteGroundEncounter]",
        "[Arena_Jumbotron_Mainframe]",
        "[Arena_Pistol]",
        "[Arena_PlayerCombatUI_3D]",
        "[Arena_Points_WorldSpaceNotification_Team1]",
        "[Arena_Points_WorldSpaceNotification_Team2] Variant",
        "[Arena_PowerWeapon_BeamGun]",
        "[Arena_RailGun]",
        "[Arena_RocketLauncher]",
        "[Arena_RocketLauncher_Projectile]",
        "[Arena_RocketLauncherExplosion]",
        "[Arena_RocketLauncherExplosion_Implosion]",
        "[Arena_Shotgun]",
        "[ArenaManager]",
        "[Arrow]",
        "[Art Canvas]",
        "[Art Canvas_Square]",
        "[AstarNavMeshManager]",
        "[AudioEffectZone]",
        "[AudioPlayerNodeVisualization_CV2]",
        "[AudioSamplerStackedUI]",
        "[AudioSamplerStartRecordingScreen]",
        "[BackgroundObjectsCircuit]",
        "[BackpackScreen]",
        "[BackpackToolButton]",
        "[BaseRoomButton]",
        "[BaseVehicle]",
        "[Basketball]",
        "(Basketballhoop)",
        "[BattleRoyaleManager]",
        "(BB_[OutfitTool])",
        "(BB_[PermanentHairDyeTool])",
        "[BecomeMemberToPurchaseItemScreen]",
        "[BeezKneezLavenderLatteConsumableTool]",
        "[BirthdayDialogScreen]",
        "[BloomCircuit]",
        "[BooleanNodeVisualization]",
        "[BoomMicrophoneStand_Sandbox]",
        "[Booth_Diner_Sandbox] Variant",
        "[Bounce_Pad_Sandbox]",
        "[Bowling_GameConfiguration] Variant",
        "[Bowling_GameRuleWrapperCircuit] Variant",
        "[BowlingAlley_Jukebox_Sandbox] Variant",
        "[BowlingAlley_Stool] Sandbox Variant",
        "[BowlingBall]",
        "[BowlingManager]",
        "[BoxShape]",
        "[BoxSubExtrusion]",
        "[BreakerBox_Sandbox] Variant",
        "[BroadcastCameraStand_Sandbox]",
        "[BubbleTeaConsumableTool]",
        "[BubbleTeaConsumableTool_Eyeball]",
        "[BubbleTeaConsumableTool_Matcha]",
        "[BubbleTeaConsumableTool_Taro]",
        "[Bubbly Cork Projectile]",
        "[BubblyConsumable_Creator_Tool]",
        "(BubblyConsumable_Forbidden_Tool)",
        "(BubblyConsumable_Forsaken_Tool)",
        "[BubblyConsumable_MidnightGala_Tool]",
        "[BubblyConsumable_Premium_Tool]",
        "(BubblyConsumable_RecCon_Blue_Tool)",
        "(BubblyConsumable_RecCon_Silver_Tool)",
        "(BubblyConsumable_Survey_Green_Tool)",
        "(BubblyConsumable_Survey_Orange_Tool)",
        "(BubblyConsumable_Survey_Purple_Tool)",
        "(BubblyConsumable_Survey_Tool)",
        "(BubblyConsumable_Survey_White_Tool)",
        "[BubblyConsumableRecConTool]",
        "[BubblyConsumableTool]",
        "[Bucket]",
        "[BuggyBodyCollision]",
        "[BulletinBoard_Sandbox] Variant",
        "(Button_Icon_XXS)",
        "[Button_StuntRunnerEnd]",
        "[Button_StuntRunnerEnd_Sandbox]",
        "[Cake87FlavorConsumableTool]",
        "[CakeCheeseConsumableTool]",
        "[CakeChocolateConsumableTool]",
        "[CakeMardigrasConsumableTool]",
        "[CakePastelConsumableTool]",
        "[CakePops_CandylandConsumableTool]",
        "[CakePops_MidnightGalaConsumableTool]",
        "[CakePopsConsumableTool]",
        "[CakeRedVelvetConsumableTool]",
        "[CakeYellowConsumableTool]",
        "(CalloutDialog)",
        "[CameraFilterConsumable_BW]",
        "[CameraFilterConsumable_Dawn]",
        "[CameraFilterConsumable_Dracula]",
        "[CameraFilterConsumable_GhostBeard]",
        "[CameraFilterConsumable_GoblinKing]",
        "[CameraFilterConsumable_Jumbotron]",
        "[CameraFilterConsumable_Sepia]",
        "[CameraFilterConsumable_Witch]",
        "[CandyAppleConsumableTool]",
        "[CannedChatEntry]",
        "(CannedChatEntry_VR)",
        "(CanvasAuthoringController)",
        "[Car_50s_Sandbox] Variant",
        "[Car_80sSportsCar_Sandbox] Variant",
        "[Cardboard_box_Sandbox] Variant",
        "[Chair_Beanbag_Sandbox] Variant",
        "[Chair_Cafe_Round_Sandbox] Variant",
        "[Chair_Moveable]",
        "[Chair_White_Moveable]",
        "[Chair_White_Stationary]",
        "[ChangeNameDialogScreen]",
        "[ChangePasswordScreen]",
        "[Charades_InkSpace_MainHull_Sandbox] Variant",
        "[Charades_Stage]",
        "[CharadesCard]",
        "[CharadesCoOpClassic_GameConfiguration] Variant",
        "[CharadesCoOpClassic_GameRuleWrapperCircuit] Variant",
        "[CharadesManager]",
        "[CharadesPen]",
        "[CharadesPenMenu]",
        "[CharadesTeamLightning_GameConfiguration] Variant",
        "[CharadesTeamLightning_GameRuleWrapperCircuit] Variant",
        "[ChecklistScreen]",
        "[Checkpoint_Sandbox]",
        "[Checkpoint_Scaffolding_Sandbox_Invention] Variant",
        "[CheerScreen]",
        "[CheesePizzaConsumableTool]",
        "[Chip]",
        "[ChocolateVarietyConsumableTool]",
        "[ChocolateVarietyConsumableTool_AntiValentines]",
        "[ChocolateVarietyConsumableTool_AprilFools]",
        "[ChooseEventLocationDialog]",
        "[ChooseFreeGiftScreen]",
        "[ChooseInventionPriceDialog]",
        "[ChooseInventionPublishingPermissionsDialog]",
        "[ChooseSubroomDialog]",
        "(Circuit_Trail)",
        "[CircuitBeacon]",
        "[CircuitBeacon_CV2]",
        "[CircuitDefaultPinDisplay]",
        "[CircuitGroup]",
        "[CircuitLinkVisual]",
        "[CircuitNodeModeEnumSettingUI]",
        "[CircuitStageLight]",
        "[CircuitStageLightV2]",
        "(CircuitV2Button)",
        "[ClampGizmo_CV1]",
        "[Climbing_VFX]",
        "[ClipboardButton]",
        "[ClothingCustomizerMarkerSet]",
        "[ClothingCustomizerTool]",
        "[ColorGradingCircuit]",
        "[ColorInputDialogScreen]",
        "[CombinatorNodeVisualization]",
        "[CommentatorBooth]",
        "[CommentatorBooth_Sandbox_Invention] Variant",
        "[ComparerNodeVisualization]",
        "[Concrete_Barrier_Sandbox] Variant",
        "[Concrete_Tube_Sandbox] Variant",
        "[ConeShape]",
        "[ConeSubExtrusion]",
        "[ConfigurableCollision_Box]",
        "[ConfirmationDialogScreen]",
        "[Consumable_BeezKneezLavenderLatte_Tray]",
        "[Consumable_Cake_Candle_Flame_VFX]",
        "[Consumable_Cake_Confetti_VFX]",
        "[Consumable_HighFive_Dracula1_Whipcrack_VFX]",
        "[Consumable_HighFive_Goblin1_Gold_VFX]",
        "[Consumable_HighFive_Goblin2_Wand_VFX]",
        "[Consumable_HighFive_Pirate1_Flintlock_VFX]",
        "[Consumable_HighFive_SciFi_Laser_VFX]",
        "[Consumable_Token_Coupon]",
        "[ConsumableButton]",
        "[Consumables_Apple_Basket]",
        "[Consumables_Apple_Red]",
        "[Consumables_BeezKneezLavenderLatte_Cup]",
        "[Consumables_BubbleTea_Cup]",
        "[Consumables_BubbleTea_Eyeball_Cup]",
        "[Consumables_BubbleTea_Eyeball_Tray]",
        "[Consumables_BubbleTea_Matcha_Cup]",
        "[Consumables_BubbleTea_Matcha_Tray]",
        "[Consumables_BubbleTea_Taro_Cup]",
        "[Consumables_BubbleTea_Taro_Tray]",
        "[Consumables_BubbleTea_Tray]",
        "[Consumables_Bubbly_Creator_Empty]",
        "[Consumables_Bubbly_Empty]",
        "[Consumables_Bubbly_FluteGlass]",
        "(Consumables_Bubbly_Forbidden_Empty)",
        "(Consumables_Bubbly_Forbidden_FluteGlass)",
        "(Consumables_Bubbly_Forbidden_Tray)",
        "(Consumables_Bubbly_Forsaken_Empty)",
        "(Consumables_Bubbly_Forsaken_FluteGlass)",
        "(Consumables_Bubbly_Forsaken_Tray)",
        "[Consumables_Bubbly_Premium_Empty]",
        "[Consumables_Bubbly_Premium_FluteGlass]",
        "[Consumables_Bubbly_Premium_Tray]",
        "(Consumables_Bubbly_RecCon_Blue_Empty)",
        "(Consumables_Bubbly_RecCon_Silver_Empty)",
        "(Consumables_Bubbly_RecConBlue_FluteGlass)",
        "(Consumables_Bubbly_RecConBlue_Tray)",
        "(Consumables_Bubbly_RecConSilver_FluteGlass)",
        "(Consumables_Bubbly_RecConSilver_Tray)",
        "(Consumables_Bubbly_Survey_Empty)",
        "(Consumables_Bubbly_Survey_FluteGlass)",
        "(Consumables_Bubbly_Survey_Green_Empty)",
        "(Consumables_Bubbly_Survey_Green_FluteGlass)",
        "(Consumables_Bubbly_Survey_Green_Tray)",
        "(Consumables_Bubbly_Survey_Orange_Empty)",
        "(Consumables_Bubbly_Survey_Orange_FluteGlass)",
        "(Consumables_Bubbly_Survey_Orange_Tray)",
        "(Consumables_Bubbly_Survey_Purple_Empty)",
        "(Consumables_Bubbly_Survey_Purple_FluteGlass)",
        "(Consumables_Bubbly_Survey_Purple_Tray)",
        "(Consumables_Bubbly_Survey_Tray)",
        "(Consumables_Bubbly_Survey_White_Empty)",
        "(Consumables_Bubbly_Survey_White_FluteGlass)",
        "(Consumables_Bubbly_Survey_White_Tray)",
        "[Consumables_Bubbly_Tray]",
        "[Consumables_Cake_87Flavor_Slice]",
        "[Consumables_Cake_87Flavor_Tray]",
        "[Consumables_Cake_Cheese_Slice]",
        "[Consumables_Cake_Cheese_Tray]",
        "[Consumables_Cake_Chocolate_Slice]",
        "[Consumables_Cake_Chocolate_Tray]",
        "[Consumables_Cake_Mardigras_Slice]",
        "[Consumables_Cake_Mardigras_Tray]",
        "[Consumables_Cake_Pastel_Slice]",
        "[Consumables_Cake_Pastel_Tray]",
        "[Consumables_Cake_RedVelvet_Slice]",
        "[Consumables_Cake_RedVelvet_Tray]",
        "[Consumables_Cake_Yellow_Slice]",
        "[Consumables_Cake_Yellow_Tray]",
        "[Consumables_CakePops_Basket]",
        "[Consumables_CakePops_Candyland_Basket]",
        "[Consumables_CakePops_Candyland_DrizzlePop]",
        "[Consumables_CakePops_Candyland_JellyPop]",
        "[Consumables_CakePops_Candyland_SprinklePop]",
        "[Consumables_CakePops_DrizzlePop]",
        "[Consumables_CakePops_JellyPop]",
        "[Consumables_CakePops_MidnightGala_Basket]",
        "[Consumables_CakePops_MidnightGala_DrizzlePop]",
        "[Consumables_CakePops_MidnightGala_JellyPop]",
        "[Consumables_CakePops_MidnightGala_SprinklePop]",
        "[Consumables_CakePops_SprinklePop]",
        "[Consumables_CandyApple_CandyApple]",
        "[Consumables_CandyApple_CandyAppleBasket]",
        "[Consumables_CheesePizza_Slice]",
        "[Consumables_ChocolateVariety_Box]",
        "[Consumables_ChocolateVariety_Box_AntiValentines]",
        "[Consumables_ChocolateVariety_Box_AprilFools]",
        "[Consumables_ChocolateVariety_DarkChocolateCircle]",
        "[Consumables_ChocolateVariety_DarkChocolateCircle_AntiValentines]",
        "[Consumables_ChocolateVariety_DarkChocolateCircle_AprilFools]",
        "[Consumables_ChocolateVariety_DarkChocolateSquare]",
        "[Consumables_ChocolateVariety_DarkChocolateSquare_AntiValentines]",
        "[Consumables_ChocolateVariety_DarkChocolateSquare_AprilFools]",
        "[Consumables_ChocolateVariety_MilkChocolateSquare]",
        "[Consumables_ChocolateVariety_MilkChocolateSquare_AntiValentines]",
        "[Consumables_ChocolateVariety_MilkChocolateSquare_AprilFools]",
        "[Consumables_ChocolateVariety_WhiteChocolateCircle]",
        "[Consumables_ChocolateVariety_WhiteChocolateCircle_AntiValentines]",
        "[Consumables_ChocolateVariety_WhiteChocolateCircle_AprilFools]",
        "[Consumables_DessertPizza_OpenBox]",
        "[Consumables_DessertPizza_Slice]",
        "(Consumables_Donut_Base)",
        "[Consumables_Donut_BostonCreme]",
        "[Consumables_Donut_ChocolateSprinkles]",
        "[Consumables_Donut_Frosted]",
        "[Consumables_Donut_Glazed]",
        "(Consumables_Donut_Invasion)",
        "[Consumables_Donut_JamFilled]",
        "[Consumables_Donut_PinkSprinkles]",
        "(Consumables_Donut_Snowman)",
        "[Consumables_Donut_Stitched]",
        "(Consumables_Donuts_Invasion_OpenBox)",
        "[Consumables_Donuts_OpenBox]",
        "(Consumables_Donuts_Snowman_OpenBox)",
        "[Consumables_Donuts_Stitched_OpenBox]",
        "[Consumables_Eating_VFX]",
        "[Consumables_HawaiianPizza_Slice]",
        "[Consumables_Latte_Cup]",
        "[Consumables_Latte_Tray]",
        "[Consumables_MidnightGala_Bubbly_Empty]",
        "[Consumables_MidnightGala_Bubbly_FluteGlass]",
        "[Consumables_MidnightGala_Bubbly_Tray]",
        "[Consumables_PepperoniPizza_Slice]",
        "[Consumables_Pizza_OpenBox]",
        "[Consumables_Popcorn_Box]",
        "[Consumables_Popcorn_Box_Chocolate]",
        "[Consumables_Popcorn_Box_Flaming]",
        "[Consumables_Popcorn_Box_MonsterMunchies]",
        "[Consumables_PopcornBall]",
        "[Consumables_PopcornBall_Chocolate]",
        "[Consumables_PopcornBall_Flaming]",
        "[Consumables_PopcornBall_MonsterMunchies]",
        "[Consumables_Pretzel_Salted]",
        "[Consumables_Pretzels_OpenBox]",
        "[Consumables_PumpkinSpiceLatte_Cup]",
        "[Consumables_PumpkinSpiceLatte_Tray]",
        "[Consumables_RecCon_Bubbly_Empty]",
        "[Consumables_RecConBubbly_FluteGlass]",
        "[Consumables_RecConBubbly_Tray]",
        "[Consumables_RootBeer_Bottle]",
        "[Consumables_RootBeer_Hackola_Bottle]",
        "[Consumables_RootBeer_Hackola_Holder]",
        "[Consumables_RootBeer_Holder]",
        "[Consumables_RootBeer_KOCola_Bottle]",
        "[Consumables_RootBeer_KOCola_Holder]",
        "[Consumables_RootBeer_PixelPop_Bottle]",
        "[Consumables_RootBeer_PixelPop_Holder]",
        "[Consumables_Sparkler]",
        "[Consumables_Sparklers_OpenBox]",
        "[Consumables_SupremePizza_Slice]",
        "[Consumables_Sushi_Box]",
        "[Consumables_Sushi_HandRoll]",
        "[Consumables_Sushi_NigiriEgg]",
        "[Consumables_Sushi_NigiriSalmon]",
        "[Consumables_Sushi_NigiriShrimp]",
        "[Consumables_Sushi_NigiriTuna]",
        "[Consumables_VRCola_Bottle]",
        "[Consumables_VRCola_Holder]",
        "[ControlPanel_Short_Sandbox] Variant",
        "[ControlPanel_Tall_Sandbox] Variant",
        "[CostumeDummy]",
        "(CostumeDummyOM)",
        "[CostumeDummyPlus]",
        "[CostumeEquipScreen]",
        "[CostumeStackedUI]",
        "[CouponConsumable_20%Tokens]",
        "[CouponConsumableTool]",
        "[CrashPad_1x1.5_ExtraThick_Sandbox]",
        "[CrashPad_1x2_Thick_Sandbox]",
        "[CrashPad_1x2_Thin_Sandbox]",
        "[CrashPad_Scaffolding_Sandbox]",
        "[CreatePasswordScreen]",
        "[CreationContext]",
        "[CrescendoOfTheBloodMoon_GameConfiguration] Variant",
        "[CrescendoOfTheBloodMoon_GameRuleWrapperCircuit] Variant",
        "[Crossbow]",
        "[Crossbow_Hunter]",
        "[CrossbowBolt]",
        "[CurseOfTheCrimsonCauldron_GameConfiguration] Variant",
        "[CurseOfTheCrimsonCauldron_GameRuleWrapperCircuit] Variant",
        "[Curtain_Flat_Sandbox] Variant",
        "[Curtain_NoTassel_Sandbox] Variant",
        "[Curtain_Sandbox] Variant",
        "[CV2_Player_World_UI]",
        "[CylinderShape]",
        "[CylinderSubExtrusion]",
        "[Dam_ElectricalUnit_Sandbox] Variant",
        "[Dart]",
        "[DefaultConsumableTool]",
        "[DefaultWorldSpaceNotification]",
        "[DelayNodeVisualization]",
        "[DEPRECATED_HolotarProjector]",
        "[DEPRECATED_Sandbox_Button]",
        "[DEPRECATED_Sandbox_Creator_Feedback_Buttons]",
        "[DEPRECATED_Sandbox_RoomDoor]",
        "[DesktopAudioSharing_PhotonVoiceRecorder]",
        "[DesktopScreenSharingTool]",
        "[DessertPizzaConsumableTool]",
        "(Dialog)",
        "(DialogButton)",
        "(DialogueUI)",
        "[DiamondShape]",
        "[DiamondSubExtrusion]",
        "[Die]",
        "[DinerNapkins_Sandbox] Variant",
        "[DiscGolf_GameConfiguration] Variant",
        "[DiscGolf_GameRuleWrapperCircuit] Variant",
        "[DiscGolfCoopCatch_GameConfiguration] Variant",
        "[DiscGolfCoopCatch_GameRuleWrapperCircuit] Variant",
        "[DiscGolfDisc]",
        "[DiscGolfGlowingDisc]",
        "[DiscGolfManager]",
        "[Dodgeball_GameConfiguration] Variant",
        "[Dodgeball_GameRuleWrapperCircuit] Variant",
        "[DodgeballBall]",
        "[DodgeballManager]",
        "[Donuts_Assorted_ConsumableTool]",
        "[Donuts_Frosted_ConsumableTool]",
        "[Donuts_Glazed_ConsumableTool]",
        "(Donuts_Invasion_ConsumableTool)",
        "(Donuts_Snowman_ConsumableTool)",
        "[Donuts_Stitched_ConsumableTool]",
        "[DonutShape]",
        "[DonutSubExtrusion]",
        "(Dorm_Bunk_Bed)",
        "(Dorm_Campus_Map)",
        "(Dorm_Ceiling_Angled)",
        "(Dorm_Ceiling_Flat)",
        "(Dorm_Community_Board)",
        "(Dorm_Desk_Lamp)",
        "(Dorm_Dresser)",
        "(Dorm_Floor)",
        "(Dorm_Floor_Trim)",
        "(Dorm_Floor_Trim_1)",
        "(Dorm_Floor_Trim_2)",
        "(Dorm_Floor_Trim_3)",
        "(Dorm_Floor_Trim_4)",
        "(Dorm_Floor_Trim_5)",
        "(Dorm_Floor_Trim_6)",
        "(Dorm_Floor_Trim_7)",
        "(Dorm_Fluorescent_Light)",
        "(Dorm_FreeMirror)",
        "(Dorm_Help_Buttons)",
        "(Dorm_Ladder)",
        "(Dorm_Light_Shafts)",
        "(Dorm_Loft_Beam)",
        "(Dorm_Loft_Floor)",
        "(Dorm_Loft_Railing)",
        "(Dorm_Loft_Shelves)",
        "(Dorm_Mirror_Buttons)",
        "(Dorm_Rug)",
        "(Dorm_Skylight_Frame)",
        "(Dorm_Skylight_Window)",
        "(Dorm_Wall_1)",
        "(Dorm_Wall_1_Down)",
        "(Dorm_Wall_1_Up)",
        "(Dorm_Wall_2)",
        "(Dorm_Wall_3)",
        "(Dorm_Wall_4)",
        "(Dorm_Wall_Loft_1)",
        "(Dorm_Wall_Loft_1_Down)",
        "(Dorm_Wall_Loft_1_Up)",
        "(Dorm_Wall_Loft_2)",
        "(Dorm_Wall_Loft_2_Down)",
        "(Dorm_Wall_Loft_2_Up)",
        "(Dorm_Wall_Pillar)",
        "(Dorm_Wall_Stripe)",
        "(Dorm_Window_Large_Frame)",
        "(Dorm_Window_Large_Panes)",
        "(Dorm_Window_Small_Frame)",
        "(Dorm_Window_Small_Panes)",
        "[Dracula1PotionConsumableTool]",
        "[DraculaQuestGearComponent]",
        "[DrawableClipboard]",
        "[DrawingObject]",
        "[Drivein_AC_Sandbox] Variant",
        "[Drivein_Projector_Sandbox] Variant",
        "[Drivein_SteamVent_Sandbox] Variant",
        "(DropTargetLine_VerticalList)",
        "[Dumpster_Sandbox] Variant",
        "[DynamicDomeLightGadget_CV2]",
        "[DynamicPointLightGadget]",
        "[DynamicPointLightGadget_CV2]",
        "[DynamicSpotlightGadget]",
        "[DynamicSpotlightGadget_CV2]",
        "[DynamicSunDirectionGadget_CV2]",
        "[EditGameRoleOrdersScreen]",
        "[EditInventionTagsDialog]",
        "[EditPlayerEventTagsDialog]",
        "[EditRoomRoleOrdersScreen]",
        "[EditRoomRoleSettingsScreen]",
        "[EgoPotionConsumableTool]",
        "[ElectricalPole_Sandbox] Variant",
        "(EmojiButton)",
        "(EmojiPickerDialog)",
        "[EndingGate]",
        "[EndingGate_Sandbox_Invention] Variant",
        "[EnterInventionDescriptionDialog]",
        "[EnterInventionNameDialog]",
        "[EquipmentButton]",
        "[Eraser]",
        "[EraserMarker]",
        "[EventDetailsScreen]",
        "[FadePlane]",
        "[FatPot]",
        "[FatPot_Large]",
        "[FeedbackTool]",
        "[Fence_Sandbox] Variant",
        "[Fence_Wood_Board_Wide_Sandbox] Variant",
        "[Fence_Wood_Frame_5m_Sandbox] Variant",
        "[FilterSearchButton]",
        "[FlagAndGoal]",
        "[FlagGoal]",
        "[FlagTool]",
        "[FogNode]",
        "[FoodConsumable_87FlavorCake]",
        "[FoodConsumable_BeezKneezLavenderLatte]",
        "[FoodConsumable_BubbleTea]",
        "[FoodConsumable_BubbleTea_Eyeball]",
        "[FoodConsumable_BubbleTea_Matcha]",
        "[FoodConsumable_Bubbly]",
        "[FoodConsumable_CakePops]",
        "[FoodConsumable_CakePops_Candyland]",
        "[FoodConsumable_CakePops_MidnightGala]",
        "[FoodConsumable_CandyApple]",
        "[FoodConsumable_CheeseCake]",
        "[FoodConsumable_CheesePizza]",
        "[FoodConsumable_ChocolateCake]",
        "[FoodConsumable_ChocolateVariety]",
        "[FoodConsumable_ChocolateVariety_AntiValentines]",
        "[FoodConsumable_ChocolateVariety_AprilFools]",
        "[FoodConsumable_Creator_Bubbly]",
        "[FoodConsumable_DessertPizza]",
        "[FoodConsumable_Donut_Assorted]",
        "[FoodConsumable_Donut_Frosted]",
        "[FoodConsumable_Donut_Glazed]",
        "(FoodConsumable_Donut_Invasion)",
        "(FoodConsumable_Donut_Snowman)",
        "[FoodConsumable_Donut_Stitched]",
        "(FoodConsumable_Forbidden_Bubbly)",
        "(FoodConsumable_Forsaken_Bubbly)",
        "[FoodConsumable_HawaiianPizza]",
        "[FoodConsumable_Latte]",
        "[FoodConsumable_MardigrasCake]",
        "[FoodConsumable_MidnightGala_Bubbly]",
        "[FoodConsumable_PastelCake]",
        "[FoodConsumable_PepperoniPizza]",
        "[FoodConsumable_Popcorn_Butter]",
        "[FoodConsumable_Popcorn_Chocolate]",
        "[FoodConsumable_Popcorn_Flaming]",
        "[FoodConsumable_Popcorn_MonsterMunchies]",
        "[FoodConsumable_Premium_Bubbly]",
        "[FoodConsumable_Pretzel_Salted]",
        "[FoodConsumable_PumpkinSpiceLatte]",
        "(FoodConsumable_RecCon_Blue_Bubbly)",
        "[FoodConsumable_RecCon_Bubbly]",
        "(FoodConsumable_RecCon_Silver_Bubbly)",
        "[FoodConsumable_RedApples]",
        "[FoodConsumable_RedVelvetCake]",
        "[FoodConsumable_RootBeer]",
        "[FoodConsumable_RootBeer_Hackola]",
        "[FoodConsumable_RootBeer_KOCola]",
        "[FoodConsumable_RootBeer_PixelPop]",
        "[FoodConsumable_SupremePizza]",
        "(FoodConsumable_Survey_Bubbly)",
        "(FoodConsumable_Survey_Green_Bubbly)",
        "(FoodConsumable_Survey_Orange_Bubbly)",
        "(FoodConsumable_Survey_Purple_Bubbly)",
        "(FoodConsumable_Survey_White_Bubbly)",
        "[FoodConsumable_Sushi]",
        "[FoodConsumable_VRCola]",
        "[FoodConsumable_YellowCake]",
        "[FoodConsumables_BubbleTea_Taro]",
        "[FreeGiftConsumableButton]",
        "[FullBodyCostumeDummy]",
        "(FullBodyPuppetProp)",
        "[FunctionHeader]",
        "[GameConfiguration]",
        "[GameGetScoreNode]",
        "[GameRoleNode]",
        "[GameRoleRow]",
        "[GameRuleWrapperCircuit]",
        "[GameScoreboardPlayerRow]",
        "[GameScoreboardPlayerStatColumn]",
        "[GameScoreboardTeamRow]",
        "[GameScoreboardView]",
        "[GameSetScoreNode]",
        "[GameSetStateNode]",
        "[GameStateInputNodeVisualization]",
        "[GameStateOutputNodeVisualizationOld]",
        "[GasPump_Sandbox] Variant",
        "[GetLeaderboardStatNode]",
        "[GetPlayerStatNode]",
        "(GiftBox)",
        "[GiftBoxChecklist]",
        "[GiftBoxDailyChallenges]",
        "[GizmoLinkVisual]",
        "[Glider]",
        "[Goblin1PotionConsumableTool]",
        "[Goblin2PotionConsumableTool]",
        "(Golden_Bucket)",
        "[GreenScreen_tool]",
        "[Grenade]",
        "(Grenade_Snowball)",
        "[HairDyePotionConsumable_Blue]",
        "[HairDyePotionConsumable_Cyan]",
        "[HairDyePotionConsumable_DarkBlue]",
        "[HairDyePotionConsumable_DarkPink]",
        "[HairDyePotionConsumable_DarkPurple]",
        "[HairDyePotionConsumable_DarkRed]",
        "[HairDyePotionConsumable_Green]",
        "[HairDyePotionConsumable_Orange]",
        "[HairDyePotionConsumable_PastelBlue]",
        "[HairDyePotionConsumable_PastelCyan]",
        "[HairDyePotionConsumable_PastelGreen]",
        "[HairDyePotionConsumable_PastelOrange]",
        "[HairDyePotionConsumable_PastelPink]",
        "[HairDyePotionConsumable_PastelPurple]",
        "[HairDyePotionConsumable_PastelRed]",
        "[HairDyePotionConsumable_PastelTeal]",
        "[HairDyePotionConsumable_PastelYellow]",
        "[HairDyePotionConsumable_Pink]",
        "[HairDyePotionConsumable_Purple]",
        "[HairDyePotionConsumable_Red]",
        "[HairDyePotionConsumable_Teal]",
        "[HairDyePotionConsumable_Yellow]",
        "[HairDyePotionConsumableTool_Blue]",
        "[HairDyePotionConsumableTool_Cyan]",
        "[HairDyePotionConsumableTool_DarkBlue]",
        "[HairDyePotionConsumableTool_DarkPink]",
        "[HairDyePotionConsumableTool_DarkPurple]",
        "[HairDyePotionConsumableTool_DarkRed]",
        "[HairDyePotionConsumableTool_Green]",
        "[HairDyePotionConsumableTool_Orange]",
        "[HairDyePotionConsumableTool_PastelBlue]",
        "[HairDyePotionConsumableTool_PastelCyan]",
        "[HairDyePotionConsumableTool_PastelGreen]",
        "[HairDyePotionConsumableTool_PastelOrange]",
        "[HairDyePotionConsumableTool_PastelPink]",
        "[HairDyePotionConsumableTool_PastelPurple]",
        "[HairDyePotionConsumableTool_PastelRed]",
        "[HairDyePotionConsumableTool_PastelTeal]",
        "[HairDyePotionConsumableTool_PastelYellow]",
        "[HairDyePotionConsumableTool_Pink]",
        "[HairDyePotionConsumableTool_Purple]",
        "[HairDyePotionConsumableTool_Red]",
        "[HairDyePotionConsumableTool_Teal]",
        "[HairDyePotionConsumableTool_Yellow]",
        "[HalfPipeShape]",
        "[HalfPipeSubExtrusion]",
        "[HalfSphereShape]",
        "[HalfSphereSubExtrusion]",
        "[HandheldStreamerCamera]",
        "[HandPotionConsumable_Dracula1]",
        "[HandPotionConsumable_Goblin1]",
        "[HandPotionConsumable_Goblin2]",
        "[HandPotionConsumable_Pirate1]",
        "[HandPotionConsumable_SciFi1]",
        "[HardEdge_Beveled_Hexagon_Shape]",
        "[HardEdge_Beveled_Hexagon_SubExtrusion]",
        "[HardEdge_Beveled_Octagon_Shape]",
        "[HardEdge_Beveled_Octagon_SubExtrusion]",
        "[HardEdge_Beveled_Pentagon_Shape]",
        "[HardEdge_Beveled_Pentagon_SubExtrusion]",
        "[HardEdge_Beveled_Triangle_Shape]",
        "[HardEdge_Beveled_Triangle_SubExtrusion]",
        "[HardEdge_Cone_Shape]",
        "[HardEdge_Cone_SubExtrusion]",
        "[HardEdge_Cube_Shape]",
        "[HardEdge_Cube_SubExtrusion]",
        "[HardEdge_CubeTube_Shape]",
        "[HardEdge_CubeTube_SubExtrusion]",
        "[HardEdge_Cylinder_Shape]",
        "[HardEdge_Cylinder_SubExtrusion]",
        "[HardEdge_CylinderHalf_Shape]",
        "[HardEdge_CylinderHalf_SubExtrusion]",
        "[HardEdge_Dodecahedron_Shape]",
        "[HardEdge_Dodecahedron_SubExtrusion]",
        "[HardEdge_Dome_Shape]",
        "[HardEdge_Dome_SubExtrusion]",
        "[HardEdge_Hexagon_Shape]",
        "[HardEdge_Hexagon_SubExtrusion]",
        "[HardEdge_Octagon_Shape]",
        "[HardEdge_Octagon_SubExtrusion]",
        "[HardEdge_Octohedron_Shape]",
        "[HardEdge_Octohedron_SubExtrusion]",
        "[HardEdge_Pentagon_Shape]",
        "[HardEdge_Pentagon_SubExtrusion]",
        "[HardEdge_Pyramid_Shape]",
        "[HardEdge_Pyrimid_SubExtrusion]",
        "[HardEdge_Quarter_Pipe_Shape]",
        "[HardEdge_Quarter_Pipe_SubExtrusion]",
        "[HardEdge_Quarter_Sphere_Shape]",
        "[HardEdge_Quarter_Sphere_SubExtrusion]",
        "[HardEdge_SoftSphere_Shape]",
        "[HardEdge_SoftSphere_SubExtrusion]",
        "[HardEdge_Trihedron_Shape]",
        "[HardEdge_Trihedron_SubExtrusion]",
        "[HardEdge_Triprism_Shape]",
        "[HardEdge_Triprism_SubExtrusion]",
        "[HardEdge_Wedge_Shape]",
        "[HardEdge_Wedge_SubExtrusion]",
        "[HawaiianPizzaConsumableTool]",
        "[Hay_Bale_Sandbox] Variant",
        "[HeadPotionConsumable_DKMode]",
        "[HighFive_VFX]",
        "[HolotarCountdownScreen]",
        "(HolotarProjector_CV1)",
        "(HolotarProjector_CV2)",
        "[HolotarRecordingScreen]",
        "[HolotarReviewScreen]",
        "[HolotarStartRecordingScreen]",
        "(HolotarStartRecordingScreenV2)",
        "[HolotarUploadingScreen]",
        "[IBeam_10M_Sandbox] Variant",
        "[IBeam_5M_Sandbox] Variant",
        "[IBeam_Bracket_Sandbox] Variant",
        "[IcebreakersCardSet]",
        "[ImportBlockListToRoomBanScreen]",
        "[ImportFriendButton]",
        "[ImportFriendsDialogScreen]",
        "[ImportRoomBansScreen]",
        "[ImposterRadio]",
        "[Impulse_Volume_Sandbox]",
        "[ImpulseButtonNode]",
        "[IndicatorNode]",
        "[InteractionVolume]",
        "(InteractionVolumeV2)",
        "[IntroduceFriendsDialog]",
        "[InventionButton]",
        "[InvisibleCollision]",
        "[InvisibleCollision_CV2]",
        "[InviteClubButton]",
        "(InviteFriendsDialog)",
        "[InviteToPartyDialog]",
        "[IsleofLostSkulls_GameConfiguration] Variant",
        "[IsleofLostSkulls_GameRuleWrapperCircuit] Variant",
        "[Jumbotron_screen]",
        "[Jumbotron_Wires]",
        "(Keepsake)",
        "[KOConsumable_BearClaw]",
        "[KOConsumable_Bees]",
        "[KOConsumable_Cola]",
        "[KOConsumable_Fangs]",
        "[KOConsumable_FryingPan]",
        "[KOConsumable_Grenade]",
        "[KOConsumable_Ranger]",
        "[KOConsumable_Shield]",
        "[KOConsumable_SkullWings]",
        "[KOConsumable_StarPower]",
        "[KOConsumable_TireTrack]",
        "[KOGraphic_BearClaw]",
        "[KOGraphic_Bees]",
        "[KOGraphic_Cola]",
        "[KOGraphic_Fangs]",
        "[KOGraphic_FryingPan]",
        "[KOGraphic_Grenade]",
        "[KOGraphic_Ranger]",
        "[KOGraphic_Shield]",
        "[KOGraphic_SkullWings]",
        "[KOGraphic_StarPower]",
        "[KOGraphic_TireTracks]",
        "[LaserTag_GameConfiguration] Variant",
        "[LaserTag_GameRuleWrapperCircuit] Variant",
        "[LatteConsumableTool]",
        "[LawnChair_Sandbox] Variant",
        "[LeaderboardProjector]",
        "(LeaderboardProjector_V2)",
        "[LeaderboardRow]",
        "[LeaderboardView]",
        "[Legacy_ScoreInputNodeVisualization]",
        "[Legacy_SetScoreOutputNodeVisualization]",
        "(LegacyConnectableLinkVisual)",
        "[LegacyPyramidShape]",
        "[LegacySandboxFFA_GameConfiguration] Variant",
        "[LegacySandboxFourTeam_GameConfiguration] Variant",
        "[LegacySandboxTwoTeam_GameConfiguration] Variant",
        "[LegacyWedgeShape]",
        "[Light_Chevron_Sandbox]",
        "[Light_Marquee_Long_Sandbox]",
        "[Light_Pendant_Sandbox] Variant",
        "[Light_Strip_Short_Sandbox]",
        "[LogEntry]",
        "[LogPile_Sandbox] Variant",
        "[LogScreen]",
        "[Longbow]",
        "[LookAtGizmo_CV1]",
        "(LootChest)",
        "(LootChest_SciFi)",
        "(LootChest_Stuntrunner)",
        "(LootChest_Stuntrunner_Store_Smaller)",
        "[MagicMarker]",
        "[MagicMarkerMenu]",
        "[MainframeEncounter]",
        "(MakerAIFeedback)",
        "[MakerPen]",
        "[MakerPen_Giftbox]",
        "[MakerPenColorButton]",
        "[MakerPenMainScreen]",
        "[MakerPenMenu]",
        "[MakerPenPaletteCircuitsV2Subscreen]",
        "[MakerPenPaletteClipboardSubscreen]",
        "[MakerPenPaletteConfigScreen]",
        "[MakerPenPaletteGameRoleSettingsScreen]",
        "[MakerPenPaletteInventionCreationScreen]",
        "[MakerPenPaletteInventionDetailsScreen]",
        "[MakerPenPaletteInventionPublishingScreen]",
        "[MakerPenPaletteInventionSetupScreen]",
        "[MakerPenPaletteInventionsSubscreen]",
        "[MakerPenPaletteMainScreen]",
        "[MakerPenPaletteMenu]",
        "[MakerPenPaletteNewPortDialog]",
        "[MakerPenPaletteNodeGroupConfigScreen]",
        "[MakerPenPaletteSearchSubscreen]",
        "[MakerPenPaletteSettingsSubscreen]",
        "[MakerPenPaletteSpawnableToolsSubscreen]",
        "[MakerPenPaletteTagsScreen]",
        "[ManageMembershipScreen]",
        "[Marker]",
        "[Marker_Recolorable] Variant",
        "(MB_Potato_Avatar_Asset)",
        "[MembershipDetailsScreen]",
        "[Merch_Token_Stack]",
        "[MessageDialogScreen]",
        "[MessageOutputNodeVisualization]",
        "[MetalBarrel_Sandbox] Variant",
        "[Microphone]",
        "[Microphone_Conference]",
        "[MicrophoneManager]",
        "(MiniLootChest_SciFi)",
        "[MirrorHolder]",
        "[MonthDayYearDialogScreen]",
        "[Mood_BG_Cloud_Far_Calm]",
        "[Mood_BG_Cloud_High_Default]",
        "[Mood_BG_Cloud_Large_Misty]",
        "[Mood_BG_Cloud_Medium_Cozy]",
        "[Mood_BG_Mountain_Low]",
        "[Mood_BG_Night_Moon]",
        "[Mood_BG_Night_SpookyMoon]",
        "[Mood_BG_Night_Stars]",
        "[Mood_BG_OuterSpace_Stars]",
        "[MoundShape]",
        "[MoundSubExtrusion]",
        "[MoveableWhiteboard]",
        "(NameTag)",
        "[NavMeshBakeVolume]",
        "[NetworkedPositionDebugger]",
        "[NewScreenModeHUD]",
        "(NintendoSwitchInlineKeyboard)",
        "[NodeGroupEditable]",
        "[NodePreview]",
        "[ObjectPlayerMappingNode]",
        "[ObjectPrefabType.Other_ContainerPivot]",
        "[ObjectPrefabType.Other_ContainerPivotPreview]",
        "[ObjectRespawnPoint]",
        "[ObjectSetTagsNode]",
        "(OMConnectableLinkVisual)",
        "[OMCreationShapeContainer]",
        "[OMObject]",
        "[OMObject-ShapeContainer]",
        "[OMStandaloneShapeContainer]",
        "[OrientationManager]",
        "[OutfitImposter]",
        "[OutputNodeVisualization]",
        "[Paddleball_GameConfiguration] Variant",
        "[Paddleball_GameRuleWrapperCircuit] Variant",
        "[Paddleball_Paddle]",
        "[PaddleballBall]",
        "[PaddleballManager]",
        "[Paintball]",
        "[Paintball_GrenadeLauncher_Explosion_VFX]",
        "[Paintball_PaintThrower]",
        "[Paintball_PaintThrower_Splash]",
        "[Paintball_ShotgunBurst01]",
        "[Paintball_Target_Sandbox] Variant",
        "[PaintballAssaultRifle]",
        "[PaintballCaptureTheFlag_GameConfiguration] Variant",
        "[PaintballCaptureTheFlag_GameRuleWrapperCircuit] Variant",
        "[PaintballGrenadeLauncher]",
        "[PaintballGun]",
        "[PaintballImpactDecal]",
        "[PaintballManager]",
        "[PaintballRifleScoped]",
        "[PaintballShield]",
        "[PaintballShotgun]",
        "[PaintballTeamBattle_GameConfiguration] Variant",
        "[PaintballTeamBattle_GameRuleWrapperCircuit] Variant",
        "[PaintThrowerBullet]",
        "[PaintThrowerImpactDecal]",
        "[PaletteUIRibbonPreview]",
        "[PaletteUITubePreview]",
        "[ParticleEmitter]",
        "[ParticleEmitter_CV2]",
        "[PeopleScreen]",
        "[PepperoniPizzaConsumableTool]",
        "[PersonalBlockListScreen]",
        "[PhotoImageScreen]",
        "[PineTree_Dead_Sandbox] Variant",
        "[Pingpong_Paddle]",
        "[PingpongBall]",
        "[Pipes_Bracket_Sandbox] Variant",
        "[Pipes_Curved_Sandbox] Variant",
        "[Pipes_Straight_Long_Sandbox] Variant",
        "[Pipes_Straight_Sandbox] Variant",
        "[PipeShape]",
        "[PipeSubExtrusion]",
        "[Pirate1PotionConsumableTool]",
        "[PistonGizmo_CV1]",
        "[PistonGizmo_CV2]",
        "[Player]",
        "(PlayerAnimationEditorDummy)",
        "[PlayerAnimationEditorPreviewPlayer]",
        "(PlayerAnimationSamplingDummy)",
        "(PlayerAvatarFullBody)",
        "(PlayerAvatarModernBeanBody)",
        "(PlayerAvatarModernSystemColliders)",
        "(PlayerBodyParts)",
        "[PlayerButton3D_2]",
        "[PlayerButtonWithCross]",
        "[PlayerCombatUI]",
        "[PlayerCreatedSign]",
        "[PlayerDisplay]",
        "[PlayerDisplayDummy]",
        "[PlayerEventBroadcastVolume]",
        "[PlayerEventGuestButton]",
        "[PlayerEventNode]",
        "(PlayerHeadInteractableCollider)",
        "[PlayerHighlightBeam]",
        "[PlayerHitInputNodeVisualization]",
        "(PlayerIdentity)",
        "[PlayerListButton]",
        "[PlayerListScreen]",
        "(PlayerMeshes)",
        "[PlayerRespawnPointVisual]",
        "[PlayerRevivedInputNodeVisualization]",
        "[PlayerRoleMappingNode]",
        "[PlayerTeamMappingNode]",
        "(PlayerToolEquipSlots)",
        "(PlayerTorsoInteractableCollider)",
        "(PlayerTrackingSpace)",
        "[PlayerTrail]",
        "[PlayerValidationDummy]",
        "[PlayerValidationDummySet]",
        "(PlayerVoice)",
        "(PlayerVoiceOutput)",
        "[PlayerWatchMenu]",
        "[PlayingCardGroup]",
        "[PokerChipGroup]",
        "[Polaroid]",
        "[PoolBall]",
        "[PoolCue]",
        "[PoolCueRack]",
        "[PoolTable]",
        "[PoolTriangle]",
        "[Popcorn_Butter_ConsumableTool]",
        "[Popcorn_Chocolate_ConsumableTool]",
        "[Popcorn_Eat_Chocolate_VFX]",
        "[Popcorn_Eat_Flaming_VFX]",
        "[Popcorn_Eat_MonsterMunchies_VFX]",
        "[Popcorn_Eat_VFX]",
        "[Popcorn_Flaming_ConsumableTool]",
        "[Popcorn_Hit_Chocolate_VFX]",
        "[Popcorn_Hit_Flaming_VFX]",
        "[Popcorn_Hit_MonsterMunchies_VFX]",
        "[Popcorn_Hit_VFX]",
        "[Popcorn_MonsterMunchies_ConsumableTool]",
        "[Port]",
        "[PortEditable]",
        "[Pretzel_Salted_ConsumableTool]",
        "[PrimitiveShapeType.Box]",
        "[PrimitiveShapeType.Cone]",
        "[PrimitiveShapeType.Cylinder]",
        "[PrimitiveShapeType.Diamond]",
        "[PrimitiveShapeType.Donut]",
        "[PrimitiveShapeType.HalfPipe]",
        "[PrimitiveShapeType.HalfSphere]",
        "[PrimitiveShapeType.LegacyBox]",
        "[PrimitiveShapeType.LegacyPyramid]",
        "[PrimitiveShapeType.LegacyWedge]",
        "[PrimitiveShapeType.Mound]",
        "[PrimitiveShapeType.Pipe]",
        "[PrimitiveShapeType.Pyramid]",
        "[PrimitiveShapeType.RoundedBox]",
        "[PrimitiveShapeType.Sphere]",
        "[PrimitiveShapeType.TriggerVolumeBox]",
        "[PrimitiveShapeType.Wedge]",
        "[ProjectileGrenade]",
        "[ProximityMine]",
        "[ProximityMine_Explosion_VFX]",
        "(PUG_Choices)",
        "[PumpkinSpiceLatteConsumableTool]",
        "[PyramidShape]",
        "[PyramidSubExtrusion]",
        "[Quest_BatEnemyBase]",
        "[Quest_Boulder]",
        "[Quest_Dracula1_1H-Crossbow]",
        "[Quest_Dracula1_BasicBoneMeleeEnemy]",
        "[Quest_Dracula1_BasicChargingWolfEnemy]",
        "[Quest_Dracula1_BasicLungingBatEnemy]",
        "[Quest_Dracula1_BasicLungingBatEnemy_Inverted]",
        "[Quest_Dracula1_BasicLungingWolfEnemy]",
        "[Quest_Dracula1_BasicRangedBatEnemy]",
        "[Quest_Dracula1_BasicRangedBatEnemy_Inverted]",
        "[Quest_Dracula1_Bat_Plushy]",
        "[Quest_Dracula1_BlunderBuss]",
        "[Quest_Dracula1_Boss_Explode]",
        "[Quest_Dracula1_BossBatDecoyEnemy]",
        "[Quest_Dracula1_ChestCoins_Large]",
        "[Quest_Dracula1_ChestCoins_Medium]",
        "[Quest_Dracula1_ChestCoins_Small]",
        "[Quest_Dracula1_CoinStack_Small]",
        "[Quest_Dracula1_Collectable_Large]",
        "[Quest_Dracula1_Collectable_Small]",
        "[Quest_Dracula1_Collectable_Wall]",
        "[Quest_Dracula1_CollectablePumpkin_Small]",
        "[Quest_Dracula1_Crossbow_Hunter]",
        "[Quest_Dracula1_DraculaBoss]",
        "[Quest_Dracula1_DraculaBossBat]",
        "[Quest_Dracula1_EnemyCombatUI_3D]",
        "[Quest_Dracula1_Flintlock]",
        "[Quest_Dracula1_Ground_Bone_ThrownEnemy]",
        "[Quest_Dracula1_Ground_MusketEnemy]",
        "[Quest_Dracula1_Hookshot_Sandbox]",
        "(Quest_Dracula1_LootChest)",
        "[Quest_Dracula1_Manager]",
        "[Quest_Dracula1_MiniBossBoneMeleeEnemy]",
        "[Quest_Dracula1_MiniBossCoins_Bat]",
        "[Quest_Dracula1_MiniBossCoins_BoneMelee]",
        "[Quest_Dracula1_MiniBossCoins_BoneThrower]",
        "[Quest_Dracula1_MiniBossCoins_Musket]",
        "[Quest_Dracula1_MiniBossCoins_Wolf]",
        "[Quest_Dracula1_MiniBossGround_Musket]",
        "[Quest_Dracula1_MiniBossGroundBoneThrownEnemy]",
        "[Quest_Dracula1_MiniBossLungingWolfEnemy]",
        "[Quest_Dracula1_MiniBossRangedBatEnemy]",
        "[Quest_Dracula1_MiniBossRangedBatFireball]",
        "[Quest_Dracula1_MiniBossSkeletonBone]",
        "[Quest_Dracula1_PitchFork]",
        "[Quest_Dracula1_PumpkinHeadSmash_VFX]",
        "[Quest_Dracula1_Rake]",
        "[Quest_Dracula1_RangedBat_MuzzleFlash_VFX]",
        "[Quest_Dracula1_RangedBatFireball]",
        "[Quest_Dracula1_RangedDraculaFireball]",
        "[Quest_Dracula1_Shovel]",
        "[Quest_Dracula1_Silver_Boss_VFX]",
        "[Quest_Dracula1_Silver_Store_VFX]",
        "[Quest_Dracula1_Silver_VFX]",
        "[Quest_Dracula1_SkeletonBone]",
        "(Quest_Dracula1_StoreLootChest)",
        "[Quest_Dracula1_Whip_Reference]",
        "[Quest_Dracula1_WhipCrack_Crit_VFX]",
        "[Quest_Dracula1_WhipCrack_VFX]",
        "[Quest_EliteEnemy_Laser]",
        "[Quest_Enemy_Laser]",
        "[Quest_Goblin1_Manager]",
        "[Quest_Goblin2_Manager]",
        "[Quest_Goblin2_VFX_BarrelExplosion]",
        "[Quest_Goblin_BasicFlyingRangedEnemy]",
        "[Quest_Goblin_BasicGroundMeleeEnemy]",
        "[Quest_Goblin_BasicGroundMeleeEnemy_Pike]",
        "[Quest_Goblin_BasicGroundRangedEnemy]",
        "[Quest_Goblin_BogMonster]",
        "[Quest_Goblin_BogMonster_Tentacle]",
        "[Quest_Goblin_EliteFlyingRangedEnemy]",
        "[Quest_Goblin_EliteGroundMeleeEnemy]",
        "[Quest_Goblin_FirePotion]",
        "[Quest_Goblin_FirePowerup]",
        "[Quest_Goblin_KnightChargeEnemy]",
        "[Quest_Goblin_KnightSpinEnemy]",
        "[Quest_Goblin_MortarImpact_VFX]",
        "[Quest_Goblin_RotatingBossEnemy]",
        "[Quest_Goblin_VolleyRangedEnemy]",
        "[Quest_Goblin_Wand]",
        "[Quest_Goblin_WandBullet]",
        "[Quest_Goblin_WitchBoss]",
        "[Quest_JumbotronBoss_Laser]",
        "[Quest_Pirate1_BarStool]",
        "[Quest_Pirate1_BeerBottle]",
        "[Quest_Pirate1_BossCannon_Fire_FX]",
        "[Quest_Pirate1_BreakableBone]",
        "[Quest_Pirate1_BreakableFish]",
        "[Quest_Pirate1_Cannon_Fire_FX]",
        "[Quest_Pirate1_Cannonball_Projectile]",
        "[Quest_Pirate1_CoconutBomb]",
        "[Quest_Pirate1_CoconutBomb_Sparks_VFX]",
        "[Quest_Pirate1_CoinStack_Small]",
        "[Quest_Pirate1_Cutlass]",
        "[Quest_Pirate1_Flintlock]",
        "[Quest_Pirate1_FlintlockFire_VFX]",
        "[Quest_Pirate1_FlintlockImpact_VFX]",
        "[Quest_Pirate1_FlintlockProjectile]",
        "[Quest_Pirate1_FlintlockSmoke_VFX]",
        "[Quest_Pirate1_FryingPan]",
        "[Quest_Pirate1_HookHand]",
        "(Quest_Pirate1_LootChest)",
        "[Quest_Pirate1_LostLoot]",
        "[Quest_Pirate1_Manager]",
        "[Quest_Pirate1_Mug]",
        "[Quest_Pirate1_Oar]",
        "[Quest_Pirate1_Plate]",
        "[Quest_Pirate1_PlayerDamaged_VFX]",
        "[Quest_Pirate1_PushBroom]",
        "[Quest_Pirate1_RumExplosion_VFX]",
        "[Quest_Pirate1_RumJug]",
        "[Quest_Pirate1_Standee_PhotoOp]",
        "(Quest_Pirate1_StoreLootChest)",
        "[Quest_Pirate1_Torch]",
        "[Quest_Pirate1_Weapon_Sparks_Block_Enemy_VFX]",
        "[Quest_Pirate1_Weapon_Sparks_Block_VFX]",
        "[Quest_Pirate1_Weapon_Sparks_Crit_VFX]",
        "[Quest_Pirate1_Weapon_Sparks_VFX]",
        "[Quest_Pirate1_WoodSplinter_VFX]",
        "[Quest_Pirate_BasicGroundMeleeEnemy]",
        "[Quest_Pirate_BossEnemy]",
        "[Quest_Pirate_CannoneerEnemy]",
        "[Quest_Pirate_Ground_Bottle_ThrownEnemy]",
        "[Quest_Pirate_Ground_Explosive_ThrownEnemy]",
        "[Quest_Pirate_Ground_GibbetEnemy]",
        "[Quest_Pirate_Ground_RangedEnemy]",
        "[Quest_Powerup_FireImpactParticles]",
        "[Quest_SciFi1_Manager]",
        "[Quest_SciFi_AutomaticGun]",
        "[Quest_SciFi_AutomaticLaser]",
        "[Quest_SciFi_BasicFlyingRangedEnemy]",
        "[Quest_SciFi_BasicGroundRangedEnemy]",
        "[Quest_SciFi_ChargeEnemyProjectile]",
        "[Quest_SciFi_CreditParticle]",
        "[Quest_SciFi_EliteEnemy_Projectile]",
        "[Quest_SciFi_EliteFlyingRangedEnemy]",
        "[Quest_SciFi_EliteGroundRangedEnemy]",
        "[Quest_SciFi_EnemyCombatUI_3D]",
        "[Quest_SciFi_EnemyProjectile]",
        "[Quest_SciFi_ImpactDecal]",
        "[Quest_SciFi_ImpactDecal_Enemy]",
        "[Quest_SciFi_ImpactDecal_GroundEnemy]",
        "[Quest_Scifi_JumbotronBossEnemy]",
        "[Quest_SciFi_KnightAssassinEnemy]",
        "[Quest_SciFi_Pistol]",
        "[Quest_SciFi_PistolLaser]",
        "[Quest_SciFi_RailGun]",
        "[Quest_SciFi_RailGunProjectile]",
        "[Quest_SciFi_Shotgun]",
        "[Quest_SciFi_ShotgunLaser]",
        "[Quest_SciFi_StretchedBeamProjectile]",
        "[Quest_SciFi_TinyGroundExplosiveEnemy]",
        "[Quest_SfiFi_VFX_BarrelExplosion]",
        "[Quest_SfiFi_VFX_EnemyExplosion]",
        "[Quest_SkeletonEnemy_MeleeBase]",
        "[Quest_SkeletonEnemy_RangedBase]",
        "[Quest_SkeletonEnemyBase]",
        "[Quest_VolleyEnemy_Projectile]",
        "[Quest_Witch_Projectile]",
        "[QuestAIController]",
        "[QuestFirePowerupIdleVfx]",
        "[QuestForTheGoldenTrophy_GameConfiguration] Variant",
        "[QuestForTheGoldenTrophy_GameRuleWrapperCircuit] Variant",
        "[QuestImpactDecal]",
        "[QuestMeatSword]",
        "[QuestRangedEnemyFireball]",
        "[QuestRangedEnemyGravityProjectile]",
        "[QuestShield]",
        "[QuestSword]",
        "[QuickActionButton]",
        "[QuickActionMenu]",
        "(R2PlayerRoot)",
        "[Radio]",
        "[RadioMenu]",
        "[RadioScreen]",
        "[Railing_Guardrail_Auto_Sandbox] Variant",
        "[RandomNodeVisualization]",
        "[RangefinderVisualization]",
        "[RCCar]",
        "[RCCarSandboxSet]",
        "[RecCenter_Cafe_CoffeePot]",
        "[RecCenter_Cafe_CoffeePot_Static] Variant",
        "[RecCenter_Cafe_Mug]",
        "[RecCenter_Cafe_Mug_Static] Variant",
        "[RecCenter_Cafe_Plate]",
        "[RecCenter_Couch_Sandbox] Variant",
        "[RecordableStackedUI]",
        "[RecRally_GameConfiguration] Variant",
        "[RecRally_GameRuleWrapperCircuit] Variant",
        "[RecRallyManager]",
        "[RecRoomObjectLoadingPlaceholder]",
        "[RecRoomObjectView]",
        "[RecRoyale_Automatic_Ammo_LootTool]",
        "[RecRoyale_Backpack]",
        "[RecRoyale_Explosive_Ammo_LootTool]",
        "[RecRoyale_Frontier_WinnerSign]",
        "[RecRoyale_Frontier_XP_Boost]",
        "[RecRoyale_GameplayZone]",
        "[RecRoyale_Grenade]",
        "[RecRoyale_HealthAndShieldPotion]",
        "[RecRoyale_HealthPotion]",
        "[RecRoyale_Pistol_Ammo_LootTool]",
        "[RecRoyale_PlayerCombatUI_3D]",
        "[RecRoyale_PlayerMap]",
        "[RecRoyale_Rifle_Ammo_LootTool]",
        "[RecRoyale_ShieldPotion]",
        "[RecRoyale_Shotgun_Ammo_LootTool]",
        "[RecRoyale_WinnerDoor]",
        "[RecRoyaleInfoScreen]",
        "[RecRoyaleSolos_GameConfiguration] Variant",
        "[RecRoyaleSolos_GameRuleWrapperCircuit] Variant",
        "[RecRoyaleSquads_GameConfiguration] Variant",
        "[RecRoyaleSquads_GameRuleWrapperCircuit] Variant",
        "[RecRoyaleUIPrefab]",
        "[RedApplesConsumableTool]",
        "[RemoteControl]",
        "[ReportEventDialogScreen]",
        "[ReportInventionDialog]",
        "[ReportRoomDialogScreen]",
        "[ReportScreen]",
        "[RespawnNodeVisualization]",
        "[RestoreRoomDialogScreen]",
        "[RiseOfJumbotron_GameConfiguration] Variant",
        "[RiseOfJumbotron_GameRuleWrapperCircuit] Variant",
        "[Rock_01] Variant_Sandbox] Variant",
        "[Rock_04] Variant_Sandbox] Variant",
        "[Rock_Cliff] Variant_Sandbox] Variant",
        "[Rock_Cone] Variant_Sandbox] Variant",
        "[Rock_Plateau] Variant_Sandbox] Variant",
        "[Rock_Stump] Variant_Sandbox] Variant",
        "[Rock_Tall] Variant_Sandbox] Variant",
        "[Rock_Wall] Variant_Sandbox] Variant",
        "[Rock_Wedge] Variant_Sandbox] Variant",
        "[RoleChipSpawnHint]",
        "[RoleEditDialog]",
        "(RoleEntry)",
        "[RoomBanListScreen]",
        "[RoomBanPlayerScreen]",
        "[RoomComment]",
        "[RoomCommentInputDialogScreen]",
        "[RoomCommentPlacementAssist]",
        "[RoomCommentsItem]",
        "[RoomCommentsScreen]",
        "[RoomInstanceBrowserScreen]",
        "[RoomInstanceRow]",
        "(RoomOfferPurchasableItemCard)",
        "[RoomRoleRow]",
        "[RootBeer_HackolaConsumableTool]",
        "[RootBeer_KOCola_ConsumableTool]",
        "[RootBeer_PixelPop_ConsumableTool]",
        "[RootBeerConsumableTool]",
        "[Rope_Net_Sandbox]",
        "[RotatingBossFireball]",
        "[RotatorGizmo_CV1]",
        "[RotatorGizmo_CV2]",
        "[RRUIRootScreen]",
        "[Sandbox_Apple_Music_Promotion_Button]",
        "[Sandbox_Audio_Sampler]",
        "[Sandbox_BackstopShort]",
        "[Sandbox_Barrel]",
        "[Sandbox_BasketballRim_VFX]",
        "[Sandbox_Bell]",
        "[Sandbox_Book_Green]",
        "[Sandbox_Book_Yellow]",
        "[Sandbox_BoxRectangle]",
        "[Sandbox_BoxSquare]",
        "[Sandbox_Button]",
        "[Sandbox_Button_CV2]",
        "[Sandbox_Campfire]",
        "[Sandbox_Candle]",
        "[Sandbox_Ceiling]",
        "[Sandbox_CodeOfConduct_Poster]",
        "[Sandbox_ConcreteBlock]",
        "[Sandbox_Cone]",
        "[Sandbox_Confetti_VFX]",
        "[Sandbox_Couch]",
        "[Sandbox_CouchChair]",
        "[Sandbox_Creator_Feedback_Buttons]",
        "[Sandbox_Creator_FreeGift_Button]",
        "[Sandbox_Creator_Room_Consumable_Button]",
        "[Sandbox_Creator_Room_Currency_Button]",
        "[Sandbox_D10]",
        "[Sandbox_D10_V2]",
        "[Sandbox_D12]",
        "[Sandbox_D12_V2]",
        "[Sandbox_D20]",
        "[Sandbox_D20_V2]",
        "[Sandbox_D4]",
        "[Sandbox_D4_V2]",
        "[Sandbox_D6]",
        "[Sandbox_D6_V2]",
        "[Sandbox_D8]",
        "[Sandbox_D8_V2]",
        "[Sandbox_DiscGolfGoal]",
        "[Sandbox_EngineBooster_VFX]",
        "[Sandbox_Explosion_Emitter]",
        "[Sandbox_Explosion_Grenade_VFX]",
        "[Sandbox_Fireflies_VFX]",
        "[Sandbox_Firework_VFX]",
        "[Sandbox_FlatTreeLarge]",
        "[Sandbox_FlatTreeMedium]",
        "[Sandbox_FlatTreeSmall]",
        "[Sandbox_Floor]",
        "[Sandbox_Fog_VFX]",
        "[Sandbox_Friendotron]",
        "[Sandbox_GameTable]",
        "[Sandbox_GameTable_Small]",
        "[Sandbox_Glass]",
        "[Sandbox_Glowstick_Blue]",
        "[Sandbox_Glowstick_Orange]",
        "[Sandbox_Glowstick_Purple]",
        "[Sandbox_Glowstick_Red]",
        "[Sandbox_Grabber]",
        "[Sandbox_GreenScreen]",
        "[Sandbox_GunHandle]",
        "[Sandbox_Ham]",
        "[Sandbox_HorizontalWall]",
        "[Sandbox_Houseplant_Dracaena]",
        "[Sandbox_Houseplant_Fig]",
        "[Sandbox_Houseplant_SnakePlant]",
        "[Sandbox_Impact_Snowball_VFX]",
        "[Sandbox_Impact_Weapon_VFX]",
        "[Sandbox_JackOLantern]",
        "[Sandbox_KnockOut_VFX]",
        "[Sandbox_Ladder_Hook]",
        "[Sandbox_Laser_Pointer]",
        "[Sandbox_Leaf_VFX]",
        "[Sandbox_Link_Button]",
        "[Sandbox_Lockers]",
        "[Sandbox_LogBench]",
        "[Sandbox_MagicDoor]",
        "[Sandbox_Meeple]",
        "[Sandbox_Microphone_Stand]",
        "[Sandbox_Minifridge]",
        "[Sandbox_Mirror]",
        "[Sandbox_Mocktail_Goblet]",
        "[Sandbox_Mocktail_Margarita]",
        "[Sandbox_Mocktail_Martini]",
        "[Sandbox_Mocktail_Milkshake]",
        "[Sandbox_Mocktail_Stemless]",
        "[Sandbox_Mocktail_Tall]",
        "[Sandbox_MocktailMixer]",
        "(Sandbox_MuteGesture_Poster)",
        "[Sandbox_MuzzleFlash_VFX]",
        "[Sandbox_Paintbrush]",
        "[Sandbox_PokerChair]",
        "[Sandbox_PopUpShop_10_Storefront]",
        "[Sandbox_PopUpShop_1_Storefront]",
        "[Sandbox_PopUpShop_2_Storefront]",
        "[Sandbox_PopUpShop_3_Storefront]",
        "[Sandbox_PopUpShop_4_Storefront]",
        "[Sandbox_PopUpShop_5_Storefront]",
        "[Sandbox_PopUpShop_6_Storefront]",
        "[Sandbox_PopUpShop_7_Storefront]",
        "[Sandbox_PopUpShop_8_Storefront]",
        "[Sandbox_PopUpShop_9_Storefront]",
        "(Sandbox_PopUpShop_ProgressionEvent_1_Storefront)",
        "(Sandbox_PopUpShop_ProgressionEvent_2_Storefront)",
        "(Sandbox_PopUpShop_ProgressionEvent_3_Storefront)",
        "(Sandbox_PopUpShop_ProgressionEvent_4_Storefront)",
        "(Sandbox_PopUpShop_ProgressionEvent_5_Storefront)",
        "[Sandbox_Projectile_Cork]",
        "[Sandbox_Projectile_Laser]",
        "[Sandbox_Projectile_Launcher]",
        "[Sandbox_Projectile_Paintball]",
        "[Sandbox_Remote_Video_Player]",
        "[Sandbox_RoomDoor]",
        "[Sandbox_RoomDoorV2]",
        "[Sandbox_RootBeerBottle]",
        "[Sandbox_Seat]",
        "(Sandbox_ShakeHands_Poster)",
        "[Sandbox_Shelves_Short]",
        "[Sandbox_Shelves_Tall]",
        "[Sandbox_Showcase_Poster]",
        "[Sandbox_SittingLog]",
        "[Sandbox_SMores]",
        "[Sandbox_Snowball]",
        "[Sandbox_SnowballPile]",
        "[Sandbox_Speaker]",
        "(Sandbox_SteeringEngine)",
        "[Sandbox_StonePillar]",
        "[Sandbox_Stool]",
        "[Sandbox_StreamingCameraPoint]",
        "(Sandbox_SwingHandle)",
        "[Sandbox_Table_Coffee_Large]",
        "[Sandbox_Table_Meeting]",
        "[Sandbox_Table_PingPong]",
        "[Sandbox_Table_Short]",
        "[Sandbox_Table_Tall]",
        "[Sandbox_Text]",
        "(Sandbox_Text_2D)",
        "[Sandbox_Text_CV2]",
        "(Sandbox_Text_V3)",
        "(Sandbox_ThrowHandle)",
        "[Sandbox_Toggle_Button]",
        "[Sandbox_Toggle_Button_CV2]",
        "[Sandbox_TriggerHandle]",
        "[Sandbox_VerticalWall]",
        "[Sandbox_Wall]",
        "[Sandbox_Wall_Window]",
        "[Sandbox_Wind_Wavy_VFX]",
        "[SandboxBowlingPin]",
        "[SandboxCollisionDetectionVolume]",
        "[SandboxDiceSet]",
        "[SandboxDiceSet_V2]",
        "[SandboxEditableBoolean]",
        "[SandboxEditableButton]",
        "[SandboxEditableColor]",
        "[SandboxEditableEditTagsButton]",
        "[SandboxEditableFloat]",
        "[SandboxEditableFriendlyFlagButton]",
        "[SandboxEditableFriendlyFlags]",
        "[SandboxEditableFriendlyGuidButton]",
        "[SandboxEditableFriendlyGuidSetButton]",
        "[SandboxEditableFriendlyInt]",
        "[SandboxEditableFriendlyIntButton]",
        "[SandboxEditableInt]",
        "[SandboxEditableIntSlider]",
        "[SandboxEditableKeyGuid]",
        "[SandboxEditableObject]",
        "[SandboxEditableRoleGuid]",
        "[SandboxEditableRoleGuidSet]",
        "[SandboxEditableSearchId]",
        "[SandboxEditableString]",
        "[SandboxEditableTagInputString]",
        "[SandboxEditableTagItem]",
        "[SandboxEditableToolCleanup]",
        "[SandboxGizmo]",
        "[SandboxGizmo_CV1]",
        "[SandboxGizmo_CV2]",
        "[SandboxGoalHitVfx]",
        "[SandboxMarkerSet]",
        "[SandboxPlayerGoalLarge]",
        "[SandboxSceneSpawnPoint]",
        "[SandboxToolGoalLarge]",
        "[SandboxToolGoalMedium]",
        "[SandboxToolGoalSmall]",
        "[SandboxWelcomeMat]",
        "[SavedOutfitSlotButton]",
        "[SavedOutfitsScreen]",
        "[Scaffolding_Shiny_Block_Sandbox]",
        "[Scaffolding_Shiny_Sandbox]",
        "[SciFatPot]",
        "[SciFi_Grenade]",
        "[SciFiPotionConsumableTool]",
        "[ScoreboardProjector]",
        "[ScoreboardSetupNode]",
        "(ScreenHUDBadge)",
        "[ScreenSpaceDebuggingDisplay]",
        "[SearchButton]",
        "[SearchInputDialogScreen]",
        "[SearchResultView]",
        "[Seat]",
        "[Seat_NoUGC]",
        "[SelectAccountButton]",
        "[SelectorNodeConfigSettingUI]",
        "[SelectorNodeVisualization]",
        "[SelfScaleVisualization]",
        "[SetLeaderboardStatNode]",
        "[SetPlayerStatNode]",
        "[SFXNodeVisualization]",
        "[SFXNodeVisualization_CV2]",
        "[ShareCamera]",
        "[ShareCameraGestureHUD]",
        "[ShotgunPellet]",
        "[Sign_Diner_Sandbox] Variant",
        "[Sign_Drivein_Redbase_Sandbox] Variant",
        "[Sign_DriveIn_Sandbox] Variant",
        "[Sign_FrankiesFuel_Sandbox] Variant",
        "[SkinnedShapeRenderer]",
        "[SkyBoxCircuit]",
        "[SliderSlot]",
        "[SliderTextLabel]",
        "[Sliding_Sparks_VFX]",
        "[SmartCircuitsDialog]",
        "[SmartProtractor]",
        "[SmartRuler]",
        "[SniperRound]",
        "[SnowballImpactDecal]",
        "[Soccer_GameConfiguration] Variant",
        "[Soccer_GameRuleWrapperCircuit] Variant",
        "[Soccer_SpeedPowerup]",
        "[SoccerBall]",
        "[SoccerManager]",
        "[SoccerPowerup_Star]",
        "[SoccerShield]",
        "[SoloCup]",
        "[Sparklers_ConsumableTool]",
        "[SpawnableToolButton]",
        "[SpawnPointV2]",
        "[Speaker_Concert_Sandbox]",
        "[Speaker_DesktopSharing]",
        "[Speaker_DriveIn_Sandbox] Variant",
        "[SpectatorStreamerScreen]",
        "[SphereShape]",
        "[SphereSubExtrusion]",
        "[SpringBoard_2x2_Sandbox]",
        "[StackableBlock]",
        "[StageLight_Can_Sandbox]",
        "[StageLight_PlayerFollowing]",
        "[StandaloneShapeContainer]",
        "[StandaloneShapeContainerVHACDParameters]",
        "[Standee_Bear01]",
        "[Standee_Bear01_AudienceAnimated] Variant",
        "[Standee_Female01]",
        "[Standee_Female01_AudienceAnimated] Variant",
        "[Standee_Female02]",
        "[Standee_Female03]",
        "[Standee_Male01]",
        "[Standee_Male01_AudienceAnimated] Variant",
        "[Standee_Skeleton01]",
        "[Standee_Skeleton01_AudienceAnimated] Variant",
        "[Standee_Skeleton02]",
        "[Standee_Skeleton02_AudienceAnimated] Variant",
        "[Standee_Skeleton_Drummer]",
        "[Standee_Skeleton_Drummer_AudienceAnimated] Variant",
        "[Standee_Skeleton_Fiddle]",
        "[Standee_Skeleton_Fiddle_AudienceAnimated] Variant",
        "[Standee_Skeleton_Squeezebox]",
        "[Standee_Skeleton_Squeezebox_AudienceAnimated] Variant",
        "[StartingGate_Sandbox_Invention] Variant",
        "[StateMachineNodeVisualization]",
        "[StateMachineState]",
        "[StateTransition]",
        "[StickyNote]",
        "[StickyPoster]",
        "[StNMonsterCostumeDummy]",
        "[Stool_Wood_Round_Sandbox] Variant",
        "[StopScreen]",
        "[StuntRunner_BoostManager]",
        "[StuntRunner_Ceiling]",
        "[StuntRunner_Floor]",
        "[StuntRunner_GameConfiguration] Variant",
        "[StuntRunner_GameRuleWrapperCircuit] Variant",
        "[StuntRunner_LeaderBoard]",
        "[StuntRunner_Manager]",
        "[Stuntrunner_Pickup_Sandbox]",
        "[StuntRunner_Pickup_VFX]",
        "[StuntRunner_ScoreBoard]",
        "[StuntRunner_Wall_Long]",
        "[StuntRunner_Wall_Short]",
        "[StuntRunnerJumbotron_Makerpen]",
        "[StuntRunnerRoomBase]",
        "[SubroomButton]",
        "[SunCircuit]",
        "[SupremePizzaConsumableTool]",
        "[SushiConsumableTool]",
        "[Table_Cafe_Recolorable_Sandbox] Variant",
        "[Table_Cafe_Short_Sandbox] Variant",
        "[Table_Cafe_Tall_Sandbox] Variant",
        "[Table_Coffee_Curvy_Sandbox] Variant",
        "[Table_Diner_Sandbox] Variant",
        "[Table_Picnic_Sandbox] Variant",
        "[TagEditDialog]",
        "[TagRow]",
        "[TennisBall]",
        "(TextEntry)",
        "[TextInputDialogScreen]",
        "(TextScreen)",
        "[ThisRoomScreen]",
        "[TierRewardSpawner]",
        "[TimeRangeDialogScreen]",
        "[TimerNodeVisualization]",
        "[Tire_Car_Sandbox] Variant",
        "[Toast]",
        "(TouchpadComponent)",
        "[Tractor_Tire_Sandbox] Variant",
        "[TranslationSnappingVisualization]",
        "[TrashBin_Sandbox] Variant",
        "[TrashCan_Metal_Sandbox] Variant",
        "[Tree_Stump_Sandbox] Variant",
        "[TriggerVolume]",
        "[TriggerVolume_CV2]",
        "[Trophy_Clapperboard]",
        "[Trophy_CostumeDummy]",
        "[Trophy_DevMod]",
        "[Trophy_MakerPen]",
        "[Trophy_Moderator]",
        "[Trophy_Oscar]",
        "[Truck_Sandbox] Variant",
        "[TubeShape]",
        "[UGC_R2Storefront]",
        "[UGC_RecRally_Pickup_Sandbox]",
        "[UGC_Storefront]",
        "[UGCAiMoveOrder]",
        "[UGCAIPathPoint]",
        "[UGCArea]",
        "(UGCPurchasableItemCard)",
        "(UGCReplicator)",
        "[UGCSpawner]",
        "[UGCSpawnerV2]",
        "[UGCTetheredUIContainer_ToolMenu]",
        "[Umbrella_Table_Sandbox] Variant",
        "[UnitCube]",
        "[UpdatePlayerEventDescriptionDialog]",
        "[UpdatePlayerEventNameDialog]",
        "[UsernamePasswordScreen]",
        "[VariableNodeVisualization]",
        "[Vector_Gadget_CV2]",
        "[Vehicle_50sCar]",
        "[Vehicle_CollisionDust_VFX]",
        "[Vehicle_CollisionSparks_VFX]",
        "[Vehicle_RallyBuggy]",
        "[Vehicle_RallyBuggy_Giftbox]",
        "[Vehicle_Truck]",
        "[Vehicle_Wolf]",
        "[Vents_Bend_Sandbox] Variant",
        "[Vents_Corner_Sandbox] Variant",
        "[Vents_Cover_Sandbox] Variant",
        "[Vents_End_Sandbox] Variant",
        "[Vents_Straight_Sandbox] Variant",
        "[Vents_TJunction_Sandbox] Variant",
        "[VFX_Alert]",
        "[VFX_Arena_Laser_WeaponImpact_Player]",
        "[VFX_Basketball_PassedRim]",
        "[VFX_BossGoldCoins]",
        "[VFX_Charades_Goal]",
        "[VFX_CheerGestureCharging]",
        "[VFX_CheerGestureSuccess]",
        "[VFX_Computer_Impact]",
        "[VFX_Confetti]",
        "[VFX_ConfettiCheered]",
        "[VFX_ConfettiLvlUp]",
        "[VFX_CreditChips]",
        "[VFX_Default_Goal]",
        "[VFX_Default_HitParticles]",
        "[VFX_Default_PowerupParticles]",
        "[VFX_DiscGoalRays]",
        "[VFX_FistBump]",
        "[VFX_Gift_Exp]",
        "[VFX_GoldCoins]",
        "[VFX_GrenadeArmed]",
        "[VFX_Handshake]",
        "[VFX_HandshakeBurst]",
        "[VFX_Laser_Crit_WeaponImpact]",
        "[VFX_Laser_MuzzelFlash]",
        "[VFX_Laser_MuzzelFlash_Enemy]",
        "[VFX_Laser_MuzzelFlash_EnemyChargeShot]",
        "[VFX_Laser_MuzzelFlash_RailGun]",
        "[VFX_Laser_MuzzelFlash_RocketLauncher]",
        "[VFX_Laser_MuzzelFlash_ShotGun]",
        "[VFX_Laser_WeaponImpact]",
        "[VFX_Laser_WeaponImpact_Enemy]",
        "[VFX_Laser_WeaponImpact_EnemyChargeShot]",
        "[VFX_Laser_WeaponImpact_GroundEnemy]",
        "[VFX_Laser_WeaponImpact_RailGun]",
        "[VFX_Laser_WeaponImpact_RocketLauncher]",
        "[VFX_Laser_WeaponImpact_Small]",
        "[VFX_ObjectSpawn]",
        "[VFX_PaintBall_Shoot]",
        "[VFX_PaintThrower_MuzzleFlash]",
        "[VFX_Quest_Enemy_WeaponImpact]",
        "[VFX_RifleImpact]",
        "[VFX_SciFiEnemyWeaponCharge]",
        "[VFX_ShieldedImpact]",
        "[VFX_SnowballHit]",
        "[VFX_StopGestureCharging]",
        "[VFX_StopGestureSuccess]",
        "[VFX_Wand_FireWorkCharge]",
        "[VFX_Wand_Impact]",
        "[VFX_Wand_MuzzelFlash]",
        "[VFX_Wand_Shoot]",
        "[VFX_WeaponCriticalHitImpact]",
        "[VFX_WeaponImpact]",
        "[VFX_Witch_Projectile_Death]",
        "[VFX_Witch_Projectile_Deflect]",
        "[VFX_Witch_Projectile_Explode]",
        "[VFX_Witch_Projectile_Explode_OnWitch]",
        "[VFXConsumable_SparklerBox]",
        "[ViewGameRoleSettingsScreen]",
        "[VoteKickScreen]",
        "[VoteLevelDialogScreen]",
        "[VoteNextSubroomButton]",
        "[WaterBottle]",
        "[WaterBottleSplashFx]",
        "[WaterJug_Sandbox] Variant",
        "[WaveNodeVisualization]",
        "[WeaponFlashlight]",
        "[WedgeShape]",
        "[WedgeSubExtrusion]",
        "[WelcomeMatV2]",
        "[Whip]",
        "[Whip_Sandbox] Variant",
        "[WhipPopper]",
        "[Wind_FirstPerson_Boost_VFX]",
        "[Wind_FirstPerson_SlideStart_VFX]",
        "[Wind_FirstPerson_VFX]",
        "[WireframeSelectionBounds]",
        "[Wood_Pallet_Sandbox] Variant",
        "[Wooden_Spool_Sandbox] Variant",
        "[WoodStack_Sandbox] Variant",
        "[Wrist_Watch]"
        };

        inline int selectedprefab = 0;
        inline bool spawnasset = false;
        inline float prefabscale = 1.0f;
        inline int prefabamount = 1;
        inline std::string selectedPrefabName;
        inline Vector3f prefabpos = { 1, 1, 1 };
        inline Quaternion4f prefabrot = { 1, 1, 1, 1 };
        inline bool custompos = false;
        inline bool customrot = false;
        inline bool customscale = false;
        inline bool forceequip = false;


		inline Food Guid[]
		{
			{ "87 Flavor Cake", "xwQWBB_fekmTqRc2LB92cg" },
			{ "Assorted Donuts", "ZuvkidodzkuOfGLDnTOFyg" },
			{ "Bubbly Classic", "iiGTvhOCHkOTNJhb16Zbyw" },
			{ "Candy Apples", "EmPvh3I6L0uK_1i8Wy_ylQ" },
			{ "Celebration Cake", "Sk_1sm88ZU2zpWn01Lv7hw" },
			{ "Cheese Pizza", "5hIAZ9wg5EyG1cILf4FS2A" },
			{ "Chocolate Cake", "BbJb1_0g4EGJP_CeNrjpew" },
			{ "Chocolate Frosted Donuts", "mMCGPgK3tki5S_15q2Z81A" },
			{ "Chocolate Variety Box", "K9RbXo-4U0q6NbGu8VL1Sw" },
			{ "Classic Popcorn", "QRx0aSTT9keMFdAJMQHdTg" },
			{ "Glazed Donuts", "7OZ5AE3uuUyqa0P-2W1ptg" },
			{ "Hawaiian Pizza", "_jnjYGBcyEWY5Ub4OezXcA" },
			{ "Latte", "P15H1ONBhk-5DYYjid1ttg" },
			{ "Pepperoni Pizza", "mq23W-RSP0G8iGNLdrcpUw" },
			{ "Red Apples", "uMHrUPLYFk2rJOW_uop5Aw" },
			{ "Red Velvet Cake", "LwaotjVEBUir0-w8126n_g" },
			{ "Root Beer", "JfnVXFmilU6ysv-VbTAe3A" },
			{ "Salted Pretzels", "InQ25wQMGkG_bvuD5rf2Ag" },
			//{ "Testing", "[Bucket]" },
			{ "Supreme Pizza", "wUCIKdJSvEmiQHYMyx4X4w" },
		};
		inline constexpr std::size_t GuidCount = sizeof(Guid) / sizeof(Guid[0]);
		inline const char* foodGuid = Guid[0].guid;
	}

	namespace combat
	{
		inline bool rapidfire = false;
        inline bool infiniteammo = false;
		inline bool norecoil = false;
		inline bool fastbullets = false;
		inline bool cubeofbullets = false;
		inline bool holdtofire = false;
        
		inline int buletamount = 1;
        inline bool custombullet = false;


	}




}